version: 2.1

orbs:
  terraform: circleci/terraform@3.0.0

terraform_versions: &terraform_versions
  - 1.0.11
  - 1.1.0

terraform_folders: &terraform_folders
  - ./
  # Pipeline Setup Example
  - ./examples/pipeline_setup/service/
  - ./examples/pipeline_setup/test/
  - ./examples/pipeline_setup/stage/
  - ./examples/pipeline_setup/prod/
  # Microservice Setup Example
  - ./examples/pipeline_setup/test/
  - ./examples/pipeline_setup/stage/
  - ./examples/pipeline_setup/prod/

workflows:
  validate:
    jobs:
      - terraform/validate:
          checkout: true
          backend: false
          matrix:
            parameters:
              tag: *terraform_versions
              path: *terraform_folders


